from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from inserv.models.base_model import Model
from inserv.models.entity_ref import EntityRef
from inserv.models.time_period import TimePeriod
from inserv import util

from inserv.models.entity_ref import EntityRef  # noqa: E501
from inserv.models.time_period import TimePeriod  # noqa: E501

class IntentMVO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, description=None, valid_for=None, version=None, priority=None, is_bundled=None, context=None, creation_date=None, last_update=None, lifecycle_status=None, status_change_date=None, intent_specification=None):  # noqa: E501
        """IntentMVO - a model defined in OpenAPI

        :param id: The id of this IntentMVO.  # noqa: E501
        :type id: str
        :param name: The name of this IntentMVO.  # noqa: E501
        :type name: str
        :param description: The description of this IntentMVO.  # noqa: E501
        :type description: str
        :param valid_for: The valid_for of this IntentMVO.  # noqa: E501
        :type valid_for: TimePeriod
        :param version: The version of this IntentMVO.  # noqa: E501
        :type version: str
        :param priority: The priority of this IntentMVO.  # noqa: E501
        :type priority: str
        :param is_bundled: The is_bundled of this IntentMVO.  # noqa: E501
        :type is_bundled: bool
        :param context: The context of this IntentMVO.  # noqa: E501
        :type context: str
        :param creation_date: The creation_date of this IntentMVO.  # noqa: E501
        :type creation_date: datetime
        :param last_update: The last_update of this IntentMVO.  # noqa: E501
        :type last_update: datetime
        :param lifecycle_status: The lifecycle_status of this IntentMVO.  # noqa: E501
        :type lifecycle_status: str
        :param status_change_date: The status_change_date of this IntentMVO.  # noqa: E501
        :type status_change_date: datetime
        :param intent_specification: The intent_specification of this IntentMVO.  # noqa: E501
        :type intent_specification: EntityRef
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'description': str,
            'valid_for': TimePeriod,
            'version': str,
            'priority': str,
            'is_bundled': bool,
            'context': str,
            'creation_date': datetime,
            'last_update': datetime,
            'lifecycle_status': str,
            'status_change_date': datetime,
            'intent_specification': EntityRef
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'valid_for': 'validFor',
            'version': 'version',
            'priority': 'priority',
            'is_bundled': 'isBundled',
            'context': 'context',
            'creation_date': 'creationDate',
            'last_update': 'lastUpdate',
            'lifecycle_status': 'lifecycleStatus',
            'status_change_date': 'statusChangeDate',
            'intent_specification': 'intentSpecification'
        }

        self._id = id
        self._name = name
        self._description = description
        self._valid_for = valid_for
        self._version = version
        self._priority = priority
        self._is_bundled = is_bundled
        self._context = context
        self._creation_date = creation_date
        self._last_update = last_update
        self._lifecycle_status = lifecycle_status
        self._status_change_date = status_change_date
        self._intent_specification = intent_specification

    @classmethod
    def from_dict(cls, dikt) -> 'IntentMVO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Intent_MVO of this IntentMVO.  # noqa: E501
        :rtype: IntentMVO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this IntentMVO.


        :return: The id of this IntentMVO.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this IntentMVO.


        :param id: The id of this IntentMVO.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this IntentMVO.


        :return: The name of this IntentMVO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this IntentMVO.


        :param name: The name of this IntentMVO.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this IntentMVO.


        :return: The description of this IntentMVO.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this IntentMVO.


        :param description: The description of this IntentMVO.
        :type description: str
        """

        self._description = description

    @property
    def valid_for(self) -> TimePeriod:
        """Gets the valid_for of this IntentMVO.


        :return: The valid_for of this IntentMVO.
        :rtype: TimePeriod
        """
        return self._valid_for

    @valid_for.setter
    def valid_for(self, valid_for: TimePeriod):
        """Sets the valid_for of this IntentMVO.


        :param valid_for: The valid_for of this IntentMVO.
        :type valid_for: TimePeriod
        """

        self._valid_for = valid_for

    @property
    def version(self) -> str:
        """Gets the version of this IntentMVO.


        :return: The version of this IntentMVO.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this IntentMVO.


        :param version: The version of this IntentMVO.
        :type version: str
        """

        self._version = version

    @property
    def priority(self) -> str:
        """Gets the priority of this IntentMVO.


        :return: The priority of this IntentMVO.
        :rtype: str
        """
        return self._priority

    @priority.setter
    def priority(self, priority: str):
        """Sets the priority of this IntentMVO.


        :param priority: The priority of this IntentMVO.
        :type priority: str
        """

        self._priority = priority

    @property
    def is_bundled(self) -> bool:
        """Gets the is_bundled of this IntentMVO.


        :return: The is_bundled of this IntentMVO.
        :rtype: bool
        """
        return self._is_bundled

    @is_bundled.setter
    def is_bundled(self, is_bundled: bool):
        """Sets the is_bundled of this IntentMVO.


        :param is_bundled: The is_bundled of this IntentMVO.
        :type is_bundled: bool
        """

        self._is_bundled = is_bundled

    @property
    def context(self) -> str:
        """Gets the context of this IntentMVO.


        :return: The context of this IntentMVO.
        :rtype: str
        """
        return self._context

    @context.setter
    def context(self, context: str):
        """Sets the context of this IntentMVO.


        :param context: The context of this IntentMVO.
        :type context: str
        """

        self._context = context

    @property
    def creation_date(self) -> datetime:
        """Gets the creation_date of this IntentMVO.


        :return: The creation_date of this IntentMVO.
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: datetime):
        """Sets the creation_date of this IntentMVO.


        :param creation_date: The creation_date of this IntentMVO.
        :type creation_date: datetime
        """

        self._creation_date = creation_date

    @property
    def last_update(self) -> datetime:
        """Gets the last_update of this IntentMVO.


        :return: The last_update of this IntentMVO.
        :rtype: datetime
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update: datetime):
        """Sets the last_update of this IntentMVO.


        :param last_update: The last_update of this IntentMVO.
        :type last_update: datetime
        """

        self._last_update = last_update

    @property
    def lifecycle_status(self) -> str:
        """Gets the lifecycle_status of this IntentMVO.


        :return: The lifecycle_status of this IntentMVO.
        :rtype: str
        """
        return self._lifecycle_status

    @lifecycle_status.setter
    def lifecycle_status(self, lifecycle_status: str):
        """Sets the lifecycle_status of this IntentMVO.


        :param lifecycle_status: The lifecycle_status of this IntentMVO.
        :type lifecycle_status: str
        """

        self._lifecycle_status = lifecycle_status

    @property
    def status_change_date(self) -> datetime:
        """Gets the status_change_date of this IntentMVO.


        :return: The status_change_date of this IntentMVO.
        :rtype: datetime
        """
        return self._status_change_date

    @status_change_date.setter
    def status_change_date(self, status_change_date: datetime):
        """Sets the status_change_date of this IntentMVO.


        :param status_change_date: The status_change_date of this IntentMVO.
        :type status_change_date: datetime
        """

        self._status_change_date = status_change_date

    @property
    def intent_specification(self) -> EntityRef:
        """Gets the intent_specification of this IntentMVO.


        :return: The intent_specification of this IntentMVO.
        :rtype: EntityRef
        """
        return self._intent_specification

    @intent_specification.setter
    def intent_specification(self, intent_specification: EntityRef):
        """Sets the intent_specification of this IntentMVO.


        :param intent_specification: The intent_specification of this IntentMVO.
        :type intent_specification: EntityRef
        """

        self._intent_specification = intent_specification
