import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  repositoryIdFromGraphDbEndpoint,
  resolveGraphDbEndpoint,
} from "./graphdb-url.js";

export interface AppConfig {
  llmProvider: "openai" | "anthropic";
  openAiApiKey: string;
  openAiModel: string;
  openAiBaseUrl: string;
  anthropicApiKey: string;
  anthropicModel: string;
  anthropicBaseUrl: string;
  openClawModel: string;
  openAiTemperature: number;
  workloadCatalogBaseUrl: string;
  graphDbEndpoint: string;
  graphDbNamedGraph: string;
  graphDbQueryLimit: number;
  graphDbContextLimit: number;
  defaultIntentHandler: string;
  defaultIntentOwner: string;
  autoGenerateDescription: boolean;
  domainPackageDir: string;
  skillFile: string;
  systemPromptFile: string;
  shaclShapesFile: string;
  shaclMaxRetries: number;
  llmUsageLogPath?: string;
  a2aEnabled: boolean;
  a2aRegistryBaseUrl: string;
  a2aAgentBaseUrl: string;
  a2aAgentCardPath: string;
  a2aAutoRegisterOnStartup: boolean;
  apiServerEnabled: boolean;
  apiServerHost: string;
  apiServerPort: number;
  agentApiKey?: string;
  agentApiKeyHeader: string;
  /** Default observation reporting interval for intent generation (minutes). */
  intentReportIntervalMinutes: number;
  mlflowTracingEnabled: boolean;
  /** Dual-write spans to Postgres via OTLP for online MLflow judges (default on). */
  mlflowTrackingStoreExportEnabled: boolean;
  mlflowTrackingUri?: string;
  mlflowExperimentId?: string;
  mlflowExperimentName?: string;
}

function boolFromEnv(value: string | undefined, fallback: boolean): boolean {
  if (!value) return fallback;
  return ["1", "true", "yes", "on"].includes(value.trim().toLowerCase());
}

function numberFromEnv(value: string | undefined, fallback: number): number {
  if (!value) return fallback;
  const parsed = Number.parseInt(value, 10);
  return Number.isNaN(parsed) ? fallback : parsed;
}

function floatFromEnv(value: string | undefined, fallback: number): number {
  if (!value) return fallback;
  const parsed = Number.parseFloat(value);
  return Number.isNaN(parsed) ? fallback : parsed;
}

export function clampTemperature(value: number): number {
  if (!Number.isFinite(value)) return 0;
  return Math.min(2, Math.max(0, value));
}

export function clampReportingIntervalMinutes(value: number): number {
  if (!Number.isFinite(value)) return 10;
  return Math.min(1440, Math.max(1, Math.round(value)));
}

export function clampReportingIntervalSeconds(value: number): number {
  if (!Number.isFinite(value)) return 600;
  return Math.min(86_400, Math.max(1, Math.round(value)));
}

function normalizedBaseUrl(value: string | undefined, fallback: string): string {
  if (value === undefined) return fallback;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : fallback;
}

function normalizedPath(value: string | undefined, fallback: string): string {
  const raw = (value ?? fallback).trim();
  if (!raw.startsWith("/")) return `/${raw}`;
  return raw;
}

function mustRead(path: string): string {
  if (!existsSync(path)) {
    throw new Error(`Required file does not exist: ${path}`);
  }
  return readFileSync(path, "utf8");
}

function loadEnvFile(path: string): void {
  if (!existsSync(path)) return;
  const text = readFileSync(path, "utf8");
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    if (!key) continue;
    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

export function loadConfig(): AppConfig {
  // Load env values in this precedence:
  // 1) shell/exported vars (highest, already in process.env)
  // 2) SimulatorAgentKernel/.env (or clone .env)
  loadEnvFile(resolve(process.cwd(), ".env"));

  const llmProvider = (process.env.LLM_PROVIDER ?? "openai").trim().toLowerCase() as
    | "openai"
    | "anthropic";
  if (!["openai", "anthropic"].includes(llmProvider)) {
    throw new Error("LLM_PROVIDER must be one of: openai, anthropic");
  }

  const openAiModel = process.env.OPENAI_MODEL ?? "gpt-4o-mini";
  const anthropicModel = process.env.ANTHROPIC_MODEL ?? "claude-3-5-sonnet-latest";
  const derivedModel = llmProvider === "openai" ? openAiModel : anthropicModel;

  const skillFile = resolve(
    process.cwd(),
    process.env.SKILL_FILE ?? "../SimulatorAgentPackages/5g4data-intent-generation/skills/SKILL.md"
  );
  const domainPackageDir = resolve(
    process.cwd(),
    process.env.DOMAIN_PACKAGE_DIR ?? "../SimulatorAgentPackages/5g4data-intent-generation"
  );
  const systemPromptFile = resolve(
    process.cwd(),
    process.env.SYSTEM_PROMPT_FILE ?? "./SYSTEM_PROMPT.md"
  );
  const shaclShapesFile = resolve(
    process.cwd(),
    process.env.SHACL_SHAPES_FILE ??
      "../SimulatorAgentPackages/5g4data-intent-generation/validation/skill_subset_intent_shapes.ttl"
  );
  const llmUsageLogPath = process.env.LLM_USAGE_LOG_PATH
    ? resolve(process.cwd(), process.env.LLM_USAGE_LOG_PATH)
    : undefined;

  // Validate at startup so misconfiguration fails fast in OpenClaw.
  mustRead(skillFile);
  mustRead(systemPromptFile);
  if (!existsSync(domainPackageDir)) {
    throw new Error(
      `DOMAIN_PACKAGE_DIR does not exist: ${domainPackageDir}. Set DOMAIN_PACKAGE_DIR to a valid package directory.`
    );
  }

  return {
    llmProvider,
    openAiApiKey: process.env.OPENAI_API_KEY ?? "",
    openAiModel,
    openAiBaseUrl: normalizedBaseUrl(process.env.OPENAI_BASE_URL, "https://api.openai.com/v1"),
    anthropicApiKey: process.env.ANTHROPIC_API_KEY ?? "",
    anthropicModel,
    anthropicBaseUrl: normalizedBaseUrl(
      process.env.ANTHROPIC_BASE_URL,
      "https://api.anthropic.com"
    ),
    openClawModel: process.env.OPENCLAW_MODEL ?? derivedModel,
    openAiTemperature: clampTemperature(floatFromEnv(process.env.OPENAI_TEMPERATURE, 1)),
    workloadCatalogBaseUrl:
      process.env.WORKLOAD_CATALOG_BASE_URL ?? "https://start5g-1.cs.uit.no/wchartmuseum",
    graphDbEndpoint: resolveGraphDbEndpoint({
      endpoint: process.env.GRAPHDB_ENDPOINT,
      baseUrl: process.env.GRAPHDB_BASE_URL,
      repositoryId:
        process.env.GRAPHDB_REPOSITORY_ID?.trim() ||
        (process.env.GRAPHDB_ENDPOINT
          ? repositoryIdFromGraphDbEndpoint(process.env.GRAPHDB_ENDPOINT)
          : undefined),
    }),
    graphDbNamedGraph: process.env.GRAPHDB_NAMED_GRAPH ?? "http://intendproject.eu/telenor/infra",
    graphDbQueryLimit: Math.max(0, numberFromEnv(process.env.GRAPHDB_QUERY_LIMIT, 0)),
    graphDbContextLimit: Math.max(1, numberFromEnv(process.env.GRAPHDB_CONTEXT_LIMIT, 10)),
    defaultIntentHandler: process.env.DEFAULT_INTENT_HANDLER ?? "inServ",
    defaultIntentOwner: process.env.DEFAULT_INTENT_OWNER ?? "inChat",
    autoGenerateDescription: boolFromEnv(process.env.AUTO_GENERATE_DESCRIPTION, true),
    domainPackageDir,
    skillFile,
    systemPromptFile,
    shaclShapesFile,
    shaclMaxRetries: Math.max(0, numberFromEnv(process.env.SHACL_MAX_RETRIES, 2)),
    llmUsageLogPath,
    a2aEnabled: boolFromEnv(process.env.A2A_ENABLED, false),
    a2aRegistryBaseUrl: normalizedBaseUrl(
      process.env.A2A_REGISTRY_BASE_URL,
      "https://start5g-1.cs.uit.no/a2a-registry"
    ),
    a2aAgentBaseUrl: normalizedBaseUrl(process.env.A2A_AGENT_BASE_URL, "http://localhost:3010"),
    a2aAgentCardPath: normalizedPath(process.env.A2A_AGENT_CARD_PATH, "/.well-known/agent-card.json"),
    a2aAutoRegisterOnStartup: boolFromEnv(process.env.A2A_AUTO_REGISTER_ON_STARTUP, true),
    apiServerEnabled: boolFromEnv(process.env.API_SERVER_ENABLED, true),
    apiServerHost: process.env.API_SERVER_HOST?.trim() || "0.0.0.0",
    apiServerPort: Math.max(1, numberFromEnv(process.env.API_SERVER_PORT, 3011)),
    agentApiKey: process.env.AGENT_API_KEY?.trim() || undefined,
    agentApiKeyHeader: process.env.AGENT_API_KEY_HEADER?.trim() || "X-Api-Key",
    intentReportIntervalMinutes: clampReportingIntervalMinutes(
      numberFromEnv(process.env.INTENT_REPORT_INTERVAL_MINUTES, 10)
    ),
    mlflowTracingEnabled: boolFromEnv(process.env.MLFLOW_TRACING_ENABLED, true),
    mlflowTrackingStoreExportEnabled: boolFromEnv(
      process.env.MLFLOW_TRACKING_STORE_EXPORT_ENABLED,
      true
    ),
    mlflowTrackingUri: process.env.MLFLOW_TRACKING_URI?.trim() || undefined,
    mlflowExperimentId: process.env.MLFLOW_EXPERIMENT_ID?.trim() || undefined,
    mlflowExperimentName: process.env.MLFLOW_EXPERIMENT_NAME?.trim() || undefined
  };
}

export function readConfigFileText(path: string): string {
  return mustRead(path).trim();
}

export function resolveProjectRoot(): string {
  return rootSafe(process.cwd(), "..");
}

function rootSafe(base: string, relative: string): string {
  return resolve(base, relative);
}
