import test from "node:test";
import assert from "node:assert/strict";
import { createOpenClawModelInvoker } from "../adapters/openclaw.js";
import type { AppConfig } from "../config.js";

const baseConfig: AppConfig = {
  llmProvider: "openai",
  openAiApiKey: "k",
  openAiModel: "gpt-5.3-chat-latest",
  openAiBaseUrl: "https://api.openai.com/v1",
  anthropicApiKey: "a",
  anthropicModel: "claude-3-5-sonnet-latest",
  anthropicBaseUrl: "https://api.anthropic.com",
  openClawModel: "gpt-5.3-chat-latest",
  workloadCatalogBaseUrl: "",
  graphDbEndpoint: "",
  graphDbNamedGraph: "",
  graphDbQueryLimit: 0,
  graphDbContextLimit: 10,
  defaultIntentHandler: "inServ",
  defaultIntentOwner: "inChat",
  autoGenerateDescription: true,
  domainPackageDir: "",
  skillFile: "",
  systemPromptFile: "",
  shaclShapesFile: "",
  shaclMaxRetries: 0
};

test("openai adapter captures usage fields", async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = (async () =>
    new Response(
      JSON.stringify({
        id: "req_1",
        choices: [{ message: { content: "ok" } }],
        usage: { prompt_tokens: 100, completion_tokens: 25, total_tokens: 125 }
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    )) as typeof fetch;
  try {
    const invoker = createOpenClawModelInvoker(baseConfig);
    const result = await invoker([{ role: "user", content: "hi" }], { stage: "main_turn" });
    assert.equal(result.call.usage.inputTokens, 100);
    assert.equal(result.call.usage.outputTokens, 25);
    assert.equal(result.call.usage.totalTokens, 125);
    assert.equal(result.call.requestId, "req_1");
  } finally {
    globalThis.fetch = originalFetch;
  }
});
