#!/usr/bin/env npx tsx
/**
 * Concatenate tio-shacl rdf/shapes + rdf/lib into a single Turtle bundle for ModelOnly SHACL.
 *
 * Usage:
 *   npx tsx scripts/bundle-tio-shacl-shapes.mts [out-file]
 *
 * Default out-file:
 *   SimulatorAgentPackages/5g4data-intent-generating-agent-model-only/validation/tio_shapes_bundle.ttl
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const shapesDir = join(root, "tio-shacl", "rdf", "shapes");
const libDir = join(root, "tio-shacl", "rdf", "lib");
const defaultOut = join(
  root,
  "SimulatorAgentPackages",
  "5g4data-intent-generating-agent-model-only",
  "validation",
  "tio_shapes_bundle.ttl"
);
const outFile = resolve(process.argv[2] ?? defaultOut);

function listTtl(dir: string): string[] {
  try {
    return readdirSync(dir)
      .filter((name) => name.endsWith(".ttl"))
      .sort()
      .map((name) => join(dir, name));
  } catch {
    return [];
  }
}

const files = [...listTtl(libDir), ...listTtl(shapesDir)];
if (files.length === 0) {
  console.error(`No .ttl files found under ${libDir} or ${shapesDir}`);
  process.exit(1);
}

const parts = [
  `# Auto-generated by scripts/bundle-tio-shacl-shapes.mts — do not edit by hand.`,
  `# Sources: tio-shacl/rdf/lib + tio-shacl/rdf/shapes (${files.length} files)`,
  ``
];

for (const file of files) {
  const rel = file.startsWith(root) ? file.slice(root.length + 1) : file;
  parts.push(`# --- ${rel} ---`);
  parts.push(readFileSync(file, "utf8").trimEnd());
  parts.push("");
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, `${parts.join("\n")}\n`, "utf8");
console.log(`Wrote ${outFile} (${files.length} source files)`);
