apiVersion: v1
entries:
  AR-Retail-app-chart:
  - apiVersion: v2
    appVersion: 1.16.1
    created: "2025-03-21T13:27:33.811839216Z"
    description: A Helm chart for Kubernetes
    digest: 958209231c099900562e3785ecefc49e95f5ac063ddfd62e9fc37d68cc88579f
    icon: https://raw.githubusercontent.com/arne-munch-ellingsen/Intent-Lifecycle-Managent/6662aa7c8d440b944afa9c59483868775b4ef9ee/src/5G4Data-tool-decision-logic/static/augmented-reality.png
    name: AR-Retail-app-chart
    type: application
    urls:
    - charts/AR-Retail-app-chart-0.1.1.tgz
    version: 0.1.1
  airflow:
  - annotations:
      category: WorkFlow
      images: |
        - name: airflow
          image: docker.io/bitnami/airflow:2.10.5-debian-12-r6
        - name: statsd-exporter
          image: docker.io/bitnami/statsd-exporter:0.28.0-debian-12-r9
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.10.5
    created: "2025-03-21T14:01:35.739185467Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 20.x.x
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 16.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache Airflow is a tool to express and execute workflows as directed acyclic graphs (DAGs). It includes utilities to schedule tasks, monitor task progress and handle task dependencies.
    digest: 50360dd5e891b7cb4d8b463c7da5a6dbde9bf5b1755bcae9a11ad6bcf924b890
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/airflow/img/airflow-stack-220x234.png
    keywords:
    - apache
    - airflow
    - workflow
    - dag
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: airflow
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/airflow
    urls:
    - charts/airflow-22.7.0.tgz
    version: 22.7.0
  apache:
  - annotations:
      category: Infrastructure
      images: |
        - name: apache
          image: docker.io/bitnami/apache:2.4.63-debian-12-r6
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.9-debian-12-r16
        - name: git
          image: docker.io/bitnami/git:2.48.1-debian-12-r8
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.4.63
    created: "2025-03-21T13:27:40.494393345Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache HTTP Server is an open-source HTTP server. The goal of this project is to provide a secure, efficient and extensible server that provides HTTP services in sync with the current HTTP standards.
    digest: 2bc2f7c95dbcc1102615f2e9ee381d923f06ea0126cb5c1461b8a8eebbf46d5c
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/apache/img/apache-stack-220x234.png
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: apache
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/apache
    urls:
    - charts/apache-11.3.4.tgz
    version: 11.3.4
  grafana:
  - annotations:
      category: Analytics
      images: |
        - name: grafana
          image: docker.io/bitnami/grafana:11.5.2-debian-12-r2
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r39
      licenses: Apache-2.0
      tanzuCategory: application
    apiVersion: v2
    appVersion: 11.5.2
    created: "2025-03-21T14:01:01.65838584Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Grafana is an open source metric analytics and visualization suite for visualizing time series data that supports various types of data sources.
    digest: 5d0feb949b52ad9a768700ca9c9e10cc4d8d7049621d76f18df38c5ef36bde3b
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/grafana/img/grafana-stack-220x234.png
    keywords:
    - analytics
    - monitoring
    - metrics
    - logs
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: grafana
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/grafana
    urls:
    - charts/grafana-11.6.0.tgz
    version: 11.6.0
  jupyterhub:
  - annotations:
      category: MachineLearning
      images: |
        - name: configurable-http-proxy
          image: docker.io/bitnami/configurable-http-proxy:4.6.3-debian-12-r3
        - name: jupyter-base-notebook
          image: docker.io/bitnami/jupyter-base-notebook:4.1.6-debian-12-r25
        - name: jupyterhub
          image: docker.io/bitnami/jupyterhub:4.1.6-debian-12-r13
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r38
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 4.1.6
    created: "2025-03-21T14:01:05.298384883Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 16.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: JupyterHub brings the power of notebooks to groups of users. It gives users access to computational environments and resources without burdening the users with installation and maintenance tasks.
    digest: d091b6e4422db78ed87f53c02eaac922fe31dd0f82ebef385bf98a10c5e26768
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/jupyterhub/img/jupyterhub-stack-220x234.png
    keywords:
    - python
    - scientific
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: jupyterhub
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/jupyterhub
    urls:
    - charts/jupyterhub-8.1.4.tgz
    version: 8.1.4
  mysql:
  - annotations:
      category: Database
      images: |
        - name: mysql
          image: docker.io/bitnami/mysql:8.4.4-debian-12-r4
        - name: mysqld-exporter
          image: docker.io/bitnami/mysqld-exporter:0.16.0-debian-12-r10
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r38
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 8.4.4
    created: "2025-03-21T14:01:08.550087218Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MySQL is a fast, reliable, scalable, and easy to use open source relational database system. Designed to handle mission-critical, heavy-load production applications.
    digest: c2e79b336322e914f9ce9b75ee2c7b3cd7d6f2cc634685c97f4bec2292d615c2
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mysql/img/mysql-stack-220x234.png
    keywords:
    - mysql
    - database
    - sql
    - cluster
    - high availability
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: mysql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mysql
    urls:
    - charts/mysql-12.3.1.tgz
    version: 12.3.1
generated: "2025-03-21T14:01:36Z"
serverInfo: {}
