#!/usr/bin/env bash
# Enable Grafana JWT URL login for SimulatorController dashboard links (auth_token query param).
#
# Usage:
#   ./Grafana/configure-jwt-auth.sh              # restart grafana-3002-dev
#   ./Grafana/configure-jwt-auth.sh --no-restart   # only write jwks file
#
# Reads GRAFANA_JWT_SECRET from SimulatorController/.env (or generates one).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONTROLLER_ENV="${ROOT}/SimulatorController/.env"
JWKS_FILE="${SCRIPT_DIR}/jwt-jwks.json"
CONTAINER_NAME="${GRAFANA_CONTAINER_NAME:-grafana-3002-dev}"

NO_RESTART=false
if [[ "${1:-}" == "--no-restart" ]]; then
  NO_RESTART=true
fi

if [[ ! -f "${CONTROLLER_ENV}" ]]; then
  echo "error: missing ${CONTROLLER_ENV}" >&2
  exit 1
fi

read_env_var() {
  local key="$1"
  grep -E "^[[:space:]]*${key}=" "${CONTROLLER_ENV}" 2>/dev/null | tail -n 1 | cut -d= -f2- | tr -d '\r' | sed -e 's/^["'\'' ]*//' -e 's/["'\'' ]*$//' || true
}

GRAPHDB_USERNAME="$(read_env_var GRAPHDB_USERNAME)"
GRAPHDB_USERNAME="${GRAPHDB_USERNAME:-telenor}"
GRAPHDB_PASSWORD="$(read_env_var GRAPHDB_PASSWORD)"
GRAPHDB_BASE_URL="$(read_env_var GRAPHDB_BASE_URL)"
GRAPHDB_BASE_URL="${GRAPHDB_BASE_URL:-https://start5g-1.cs.uit.no/graphdb/}"
GRAPHDB_BASE_URL="${GRAPHDB_BASE_URL%/}"
GRAPHDB_REPOSITORY="${GRAPHDB_REPOSITORY:-intents_and_intent_reports}"
GRAPHDB_SPARQL_SOURCE="${GRAPHDB_BASE_URL}/repositories/${GRAPHDB_REPOSITORY}"

GRAFANA_BASE_URL="$(read_env_var GRAFANA_BASE_URL)"
GRAFANA_BASE_URL="${GRAFANA_BASE_URL:-http://localhost:3002}"
GRAFANA_BASE_URL="${GRAFANA_BASE_URL%/}/"

if [[ -z "${GRAPHDB_PASSWORD}" ]]; then
  echo "error: set GRAPHDB_PASSWORD in ${CONTROLLER_ENV} (required for SPARQL datasource provisioning)" >&2
  exit 1
fi

SECRET="$(read_env_var GRAFANA_JWT_SECRET)"
if [[ -z "${SECRET}" ]]; then
  SECRET="$(openssl rand -base64 32 | tr -d '/+=' | head -c 43)"
  echo "GRAFANA_JWT_SECRET=\"${SECRET}\"" >> "${CONTROLLER_ENV}"
  echo "Appended GRAFANA_JWT_SECRET to ${CONTROLLER_ENV}"
fi

node -e "
const { writeFileSync } = require('fs');
const secret = process.argv[1];
const k = Buffer.from(secret, 'utf8').toString('base64').replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,'');
const jwks = { keys: [{ kty: 'oct', kid: 'simulator-controller', alg: 'HS256', use: 'sig', k }] };
writeFileSync(process.argv[2], JSON.stringify(jwks, null, 2) + '\\n');
" "${SECRET}" "${JWKS_FILE}"

echo "Wrote ${JWKS_FILE}"

render_graphdb_datasource_provisioning() {
  local out="${SCRIPT_DIR}/provisioning/datasources/graphdb-sparql.yaml"
  node -e "
const { writeFileSync } = require('fs');
const user = process.argv[1];
const pass = process.argv[2];
const source = process.argv[3];
const out = process.argv[4];
const quote = (v) => JSON.stringify(String(v));
// flandersmake-sparql-datasource routes use SecureJsonData.bearer (base64 user:pass), not basicAuthPassword.
const bearer = Buffer.from(user + ':' + pass).toString('base64');
const yaml = [
  '# Generated by configure-jwt-auth.sh — do not commit (see graphdb-sparql.yaml.example).',
  'apiVersion: 1',
  'datasources:',
  '  - name: flandersmake-sparql-datasource',
  '    type: flandersmake-sparql-datasource',
  '    access: proxy',
  '    isDefault: true',
  '    basicAuth: true',
  '    basicAuthUser: ' + quote(user),
  '    jsonData:',
  '      pdcInjected: false',
  '      source: ' + quote(source),
  '      username: ' + quote(user),
  '    secureJsonData:',
  '      basicAuthPassword: ' + quote(pass),
  '      password: ' + quote(pass),
  '      bearer: ' + quote(bearer),
  '',
].join('\\n');
writeFileSync(out, yaml);
" "${GRAPHDB_USERNAME}" "${GRAPHDB_PASSWORD}" "${GRAPHDB_SPARQL_SOURCE}" "${out}"
  echo "Wrote ${out} (basicAuthUser=${GRAPHDB_USERNAME})"
}

render_graphdb_datasource_provisioning

if [[ "${NO_RESTART}" == true ]]; then
  exit 0
fi

if ! docker inspect "${CONTAINER_NAME}" >/dev/null 2>&1; then
  echo "error: container ${CONTAINER_NAME} not found" >&2
  exit 1
fi

docker stop "${CONTAINER_NAME}" >/dev/null

# Preserve existing volume mount and image; add JWT settings.
IMAGE="$(docker inspect "${CONTAINER_NAME}" --format '{{.Config.Image}}')"
VOLUME="$(docker inspect "${CONTAINER_NAME}" --format '{{range .Mounts}}{{if eq .Destination "/var/lib/grafana"}}{{.Name}}{{end}}{{end}}')"

docker rm "${CONTAINER_NAME}" >/dev/null

PROVISIONING_DIR="${SCRIPT_DIR}/provisioning"

CONTAINER_ID="$(docker run -d \
  --restart unless-stopped \
  --network=host \
  --name="${CONTAINER_NAME}" \
  -e GF_SERVER_HTTP_PORT=3002 \
  -e GF_SERVER_HTTP_ADDR=0.0.0.0 \
  -e GF_SERVER_ROOT_URL="${GRAFANA_BASE_URL}" \
  -e GF_SECURITY_ADMIN_PASSWORD="$(read_env_var GRAFANA_ADMIN_PASSWORD)" \
  -e GF_SECURITY_DISABLE_BRUTE_FORCE_LOGIN_PROTECTION=true \
  -e GF_PANELS_ENABLE_ALPHA=true \
  -e GF_AUTH_JWT_ENABLED=true \
  -e GF_AUTH_JWT_URL_LOGIN=true \
  -e GF_AUTH_JWT_AUTO_SIGN_UP=true \
  -e GF_AUTH_JWT_HEADER_NAME=X-JWT-Assertion \
  -e GF_AUTH_JWT_USERNAME_CLAIM=sub \
  -e GF_AUTH_JWT_EMAIL_CLAIM=email \
  -e GF_AUTH_JWT_JWK_SET_FILE=/etc/grafana/jwt-jwks.json \
  -e GF_AUTH_JWT_KEY_ID=simulator-controller \
  -e GF_AUTH_JWT_ROLE_ATTRIBUTE_PATH=role \
  -e GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer \
  -e GF_AUTH_ANONYMOUS_ENABLED=true \
  -e GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer \
  -e GRAPHDB_USERNAME="${GRAPHDB_USERNAME}" \
  -e GRAPHDB_PASSWORD="${GRAPHDB_PASSWORD}" \
  -e GRAPHDB_SPARQL_SOURCE="${GRAPHDB_SPARQL_SOURCE}" \
  -v "${JWKS_FILE}:/etc/grafana/jwt-jwks.json:ro" \
  -v "${PROVISIONING_DIR}:/etc/grafana/provisioning:ro" \
  -v "${VOLUME}:/var/lib/grafana" \
  "${IMAGE}")"

echo "Started ${CONTAINER_NAME} (${CONTAINER_ID}) with JWT URL login (role claim: Editor for users in GRAFANA_JWT_EDITOR_USERS)."
echo "GraphDB SPARQL datasource: user=${GRAPHDB_USERNAME}, source=${GRAPHDB_SPARQL_SOURCE}"
echo "Set the same GRAFANA_JWT_SECRET in SimulatorController/.env and restart the Controller."
echo "GraphDB datasource credentials are rendered into provisioning/datasources/graphdb-sparql.yaml on each run."
