{
 "title": "Simulator Intent Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "intent_id" },
   { "name": "repository_id", "label": "Repository ID", "query": "telenor-5g4data-simulator-demo" },
   {
    "name": "graph_iri",
    "label": "Graph IRI",
    "query": "urn:intend:kg:telenor-5g4data:simulator-demo"
   }
  ]
 },
 "panels": [
  { "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "PREFIX icm: <http://tio.models.tmforum.org/tio/v3.6.0/IntentCommonModel/>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n\nSELECT (COUNT(DISTINCT ?intent) as ?totalIntents)\nWHERE {\n  BIND(IRI(CONCAT(\"repository:\", \"${repository_id}\")) AS ?__repository)\n  BIND(IRI(\"${graph_iri}\") AS ?__graph)\n  SERVICE ?__repository {\n    GRAPH ?__graph {\n  ?intent rdf:type icm:Intent .\n\n  \n    }}\n}",
     "queryText": "PREFIX icm: <http://tio.models.tmforum.org/tio/v3.6.0/IntentCommonModel/>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n\nSELECT (COUNT(DISTINCT ?intent) as ?totalIntents)\nWHERE {\n  BIND(IRI(CONCAT(\"repository:\", \"${repository_id}\")) AS ?__repository)\n  BIND(IRI(\"${graph_iri}\") AS ?__graph)\n  SERVICE ?__repository {\n    GRAPH ?__graph {\n  ?intent rdf:type icm:Intent .\n\n  \n    }}\n}"
    }
   ]
  },
  {
   "title": "Deployment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "PREFIX icm: <http://tio.models.tmforum.org/tio/v3.6.0/IntentCommonModel/>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX log: <http://tio.models.tmforum.org/tio/v3.6.0/LogicalOperators/>\nPREFIX data5g: <http://5g4data.eu/5g4data#>\n\nSELECT (COUNT(DISTINCT ?intent) as ?DeploymentExpectationCount)\nWHERE {\n  BIND(IRI(CONCAT(\"repository:\", \"${repository_id}\")) AS ?__repository)\n  BIND(IRI(\"${graph_iri}\") AS ?__graph)\n  SERVICE ?__repository {\n    GRAPH ?__graph {\n  ?intent rdf:type icm:Intent ;\n         log:allOf ?expectation .\n  ?expectation a data5g:DeploymentExpectation .\n\n  \n    }}\n}",
     "queryText": "PREFIX icm: <http://tio.models.tmforum.org/tio/v3.6.0/IntentCommonModel/>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX log: <http://tio.models.tmforum.org/tio/v3.6.0/LogicalOperators/>\nPREFIX data5g: <http://5g4data.eu/5g4data#>\n\nSELECT (COUNT(DISTINCT ?intent) as ?DeploymentExpectationCount)\nWHERE {\n  BIND(IRI(CONCAT(\"repository:\", \"${repository_id}\")) AS ?__repository)\n  BIND(IRI(\"${graph_iri}\") AS ?__graph)\n  SERVICE ?__repository {\n    GRAPH ?__graph {\n  ?intent rdf:type icm:Intent ;\n         log:allOf ?expectation .\n  ?expectation a data5g:DeploymentExpectation .\n\n  \n    }}\n}"
    }
   ]
  },
  {
   "title": "Expectation Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "PREFIX icm: <http://tio.models.tmforum.org/tio/v3.6.0/IntentCommonModel/>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX log: <http://tio.models.tmforum.org/tio/v3.6.0/LogicalOperators/>\nPREFIX data5g: <http://5g4data.eu/5g4data#>\n\nSELECT \n  (REPLACE(\n    IF(STRSTARTS(STR(?expectationType), STR(icm:)),\n       STRAFTER(STR(?expectationType), \"IntentCommonModel/\"),\n       STRAFTER(STR(?expectationType), \"5g4data#\")\n    ),\n    \"Expectation\", \"\"\n  ) as ?Label)\n  (COUNT(DISTINCT ?intent) as ?Value)\nWHERE {\n  BIND(IRI(CONCAT(\"repository:\", \"${repository_id}\")) AS ?__repository)\n  BIND(IRI(\"${graph_iri}\") AS ?__graph)\n  SERVICE ?__repository {\n    GRAPH ?__graph {\n  ?intent rdf:type ?intentType ;\n          ?op ?expectation .\n  \n  FILTER(STRSTARTS(STR(?op), STR(log:)))  # ← this line catches all log:* operators\n\n  ?expectation rdf:type ?expectationType .\n  FILTER(CONTAINS(STR(?expectationType), \"Expectation\"))\n\n  \n    }}\n}\nGROUP BY ?expectationType\n"
    }
   ]
  },
  {
   "title": "Intent targets",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "PREFIX icm: <http://tio.models.tmforum.org/tio/v3.6.0/IntentCommonModel/>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX log: <http://tio.models.tmforum.org/tio/v3.6.0/LogicalOperators/>\nPREFIX data5g: <http://5g4data.eu/5g4data#>\n\nSELECT \n  (STRAFTER(STR(?target), \"5g4data#\") AS ?target_name)\n  (COUNT(DISTINCT ?intent) AS ?count)\nWHERE {\n  BIND(IRI(CONCAT(\"repository:\", \"${repository_id}\")) AS ?__repository)\n  BIND(IRI(\"${graph_iri}\") AS ?__graph)\n  SERVICE ?__repository {\n    GRAPH ?__graph {\n  ?intent rdf:type ?intentType ;\n          ?op ?expectation .\n  FILTER(STRSTARTS(STR(?op), STR(log:)))  # ← capture any logical operator\n\n  ?expectation icm:target ?target .\n\n  \n    }}\n}\nGROUP BY ?target\n"
    }
   ]
  },
  {
   "title": "Top 5 Edges (# deployments)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "PREFIX icm: <http://tio.models.tmforum.org/tio/v3.6.0/IntentCommonModel/>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX log: <http://tio.models.tmforum.org/tio/v3.6.0/LogicalOperators/>\nPREFIX data5g: <http://5g4data.eu/5g4data#>\n\nSELECT \n  ?target_name\n  (COUNT(DISTINCT ?intent) AS ?count)\nWHERE {\n  BIND(IRI(CONCAT(\"repository:\", \"${repository_id}\")) AS ?__repository)\n  BIND(IRI(\"${graph_iri}\") AS ?__graph)\n  SERVICE ?__repository {\n    GRAPH ?__graph {\n  ?intent rdf:type icm:Intent ;\n          ?op1 ?expectation .\n  FILTER(STRSTARTS(STR(?op1), STR(log:)))\n\n  ?expectation a ?expectationType ;\n               ?op2 ?context .\n  FILTER(STRSTARTS(STR(?expectationType), STR(data5g:)))\n  FILTER(STRSTARTS(STR(?op2), STR(log:)))\n\n  ?context a icm:Context ;\n           data5g:DataCenter ?target_name .\n\n  \n    }}\n}\nGROUP BY ?target_name\nORDER BY DESC(?count)\nLIMIT 5\n"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "PREFIX icm: <http://tio.models.tmforum.org/tio/v3.6.0/IntentCommonModel/>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX log: <http://tio.models.tmforum.org/tio/v3.6.0/LogicalOperators/>\nPREFIX data5g: <http://5g4data.eu/5g4data#>\n\nSELECT (COUNT(DISTINCT ?intent) as ?NetworkExpectationCount)\nWHERE {\n  BIND(IRI(CONCAT(\"repository:\", \"${repository_id}\")) AS ?__repository)\n  BIND(IRI(\"${graph_iri}\") AS ?__graph)\n  SERVICE ?__repository {\n    GRAPH ?__graph {\n  ?intent rdf:type icm:Intent ;\n         log:allOf ?expectation .\n  ?expectation a data5g:NetworkExpectation .\n\n  \n    }}\n}",
     "queryText": "PREFIX icm: <http://tio.models.tmforum.org/tio/v3.6.0/IntentCommonModel/>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX log: <http://tio.models.tmforum.org/tio/v3.6.0/LogicalOperators/>\nPREFIX data5g: <http://5g4data.eu/5g4data#>\n\nSELECT (COUNT(DISTINCT ?intent) as ?NetworkExpectationCount)\nWHERE {\n  BIND(IRI(CONCAT(\"repository:\", \"${repository_id}\")) AS ?__repository)\n  BIND(IRI(\"${graph_iri}\") AS ?__graph)\n  SERVICE ?__repository {\n    GRAPH ?__graph {\n  ?intent rdf:type icm:Intent ;\n         log:allOf ?expectation .\n  ?expectation a data5g:NetworkExpectation .\n\n  \n    }}\n}"
    }
   ]
  },
  {
   "title": "Intent Details (up to 10 latest, only if state reported, state based on state report)",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "queryText": "PREFIX log: <http://tio.models.tmforum.org/tio/v3.6.0/LogicalOperators/>\nPREFIX icm: <http://tio.models.tmforum.org/tio/v3.6.0/IntentCommonModel/>\nPREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\nPREFIX dct: <http://purl.org/dc/terms/>\nPREFIX data5g: <http://5g4data.eu/5g4data#>\nPREFIX set: <http://tio.models.tmforum.org/tio/v3.6.0/SetOperators/>\nPREFIX quan: <http://tio.models.tmforum.org/tio/v3.6.0/QuantityOntology/>\n\nSELECT DISTINCT \n  (STRAFTER(STR(?intent), \"5g4data#\") AS ?intent_id)\n  (GROUP_CONCAT(DISTINCT ?description; separator=\"; \") AS ?intent_description)\n  (CONCAT(\n    \"http://start5g-1.cs.uit.no:3002/d/Simulator-5g4data-Metrics/simulator-intent-and-condition-metrics-timeseries-dashboard?var-intent_id=\",\n    STRAFTER(STR(?intent), \"5g4data#\"),\n    \"&var-repository_id=${repository_id}&var-graph_iri=${graph_iri}&from=now-30d&to=now&var-condition_metrics=\",\n    GROUP_CONCAT(DISTINCT ?linkToken; \n      separator=\",\"\n    )\n  ) AS ?intent_link)\n  (GROUP_CONCAT(DISTINCT ?condition_description; separator=\"; \") AS ?condition_descriptions)\nWHERE {\n  BIND(IRI(CONCAT(\"repository:\", \"${repository_id}\")) AS ?__repository)\n  BIND(IRI(\"${graph_iri}\") AS ?__graph)\n  SERVICE ?__repository {\n    GRAPH ?__graph {\n    ?intent rdf:type ?intentType ;\n            log:allOf ?expectation .\n\n    ?expectation rdf:type ?expectationType ;\n                 dct:description ?description .\n\n    OPTIONAL {\n      ?expectation log:allOf ?condition .\n      ?condition rdf:type icm:Condition .\n\n      OPTIONAL {\n        ?condition set:forAll [\n          icm:valuesOfTargetProperty ?metric\n        ] .\n      }\n\n      OPTIONAL {\n        ?condition dct:description ?condition_description .\n      }\n\n      BIND(STRAFTER(STR(?condition), \"5g4data#\") AS ?condLocal)\n      BIND(IF(BOUND(?metric), STRAFTER(STR(?metric), \"5g4data#\"), \"\") AS ?metricLocalStr)\n      BIND(IF(STRSTARTS(?condLocal, \"CO\"), STRAFTER(?condLocal, \"CO\"), \"\") AS ?stripUuid)\n      BIND(\n        IF(\n          ?metricLocalStr = \"\",\n          \"\",\n          IF(\n            STRENDS(?metricLocalStr, CONCAT(\"_\", ?condLocal)),\n            SUBSTR(?metricLocalStr, 1, STRLEN(?metricLocalStr) - STRLEN(CONCAT(\"_\", ?condLocal))),\n            IF(\n              ?stripUuid != \"\" && STRENDS(?metricLocalStr, CONCAT(\"_CO\", ?stripUuid)),\n              SUBSTR(?metricLocalStr, 1, STRLEN(?metricLocalStr) - STRLEN(CONCAT(\"_CO\", ?stripUuid))),\n              IF(\n                ?stripUuid != \"\" && STRENDS(?metricLocalStr, CONCAT(\"_\", ?stripUuid)),\n                SUBSTR(?metricLocalStr, 1, STRLEN(?metricLocalStr) - STRLEN(CONCAT(\"_\", ?stripUuid))),\n                ?metricLocalStr\n              )\n            )\n          )\n        )\n        AS ?metricKey)\n      BIND(\n        IF(\n          ?metricLocalStr != \"\" && STRENDS(?metricLocalStr, ?condLocal),\n          ?metricLocalStr,\n          IF(\n            ?metricKey != \"\",\n            CONCAT(?metricKey, \"_\", ?condLocal),\n            ?condLocal\n          )\n        )\n        AS ?linkToken)\n    }\n\n    FILTER(CONTAINS(STR(?expectationType), \"Expectation\"))\n  \n    }}\n}\nGROUP BY ?intent"
    },
    {
     "queryText": "PREFIX icm: <http://tio.models.tmforum.org/tio/v3.6.0/IntentCommonModel/>\nPREFIX imo: <http://tio.models.tmforum.org/tio/v3.6.0/IntentModelOntology/>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\n\nSELECT (STRAFTER(STR(?intent), \"5g4data#\") AS ?intent_id)\n       (STRAFTER(STR(?state), \"IntentModelOntology/\") AS ?intent_state)\nWHERE {\n  BIND(IRI(CONCAT(\"repository:\", \"${repository_id}\")) AS ?__repository)\n  BIND(IRI(\"${graph_iri}\") AS ?__graph)\n  SERVICE ?__repository {\n    GRAPH ?__graph {\n    {\n      SELECT ?intent (MAX(?generated) AS ?latestGenerated)\n      WHERE {\n        ?report a icm:IntentReport ;\n                icm:about ?intent ;\n                icm:reportGenerated ?generated .\n      }\n      GROUP BY ?intent\n    }\n    ?report a icm:IntentReport ;\n            icm:about ?intent ;\n            icm:reportGenerated ?latestGenerated ;\n            icm:intentHandlingState ?state .\n  \n    }}\n}"
    }
   ]
  }
 ]
}