services:
  flask-app:
    build: .
    ports:
      - "5003:5003"

  reverse-proxy:
    image: caddy:latest
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/ssl/certs
    depends_on:
      - flask-app
  chartmuseum:
    image: chartmuseum/chartmuseum:latest
    ports:
      - 8080:8080
    volumes:
      - ./charts:/charts
    environment:
      PORT: 8080
      DEBUG: 1
      STORAGE: local
      STORAGE_LOCAL_ROOTDIR: /charts

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3004:3000
    depends_on:
      - chartmuseum
    environment:
      CHARTMUSEUM_URL: http://chartmuseum:8080
