services:
  flask-app:
    build: .
    restart: unless-stopped
    networks:
      - app-network

  reverse-proxy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/ssl/certs
    depends_on:
      - flask-app
    networks:
      - app-network

  chartmuseum:
    image: chartmuseum/chartmuseum:latest
    restart: unless-stopped
    volumes:
      - ../Workload-Catalog/charts:/charts
    environment:
      PORT: 8080
      DEBUG: 1
      STORAGE: local
      STORAGE_LOCAL_ROOTDIR: /charts
    networks:
      - app-network

  webapp:
    image: 5g4data-tutorial-workload-catalog
    restart: unless-stopped
    depends_on:
      - chartmuseum
    environment:
      CHARTMUSEUM_URL: http://chartmuseum:8080
    networks:
      - app-network

networks:
  app-network:
    name: 5g4data-tutorial-app-network
