import test from "node:test";
import assert from "node:assert/strict";
import { createOpenClawModelInvoker } from "../adapters/openclaw.js";
import type { AppConfig } from "../config.js";

const baseConfig: AppConfig = {
  llmProvider: "openai",
  openAiApiKey: "k",
  openAiModel: "gpt-5.3-chat-latest",
  openAiBaseUrl: "https://api.openai.com/v1",
  anthropicApiKey: "a",
  anthropicModel: "claude-3-5-sonnet-latest",
  anthropicBaseUrl: "https://api.anthropic.com",
  openClawModel: "gpt-5.3-chat-latest",
  openAiTemperature: 1,
  workloadCatalogBaseUrl: "",
  graphDbEndpoint: "",
  graphDbNamedGraph: "",
  graphDbInfraEndpoint: "http://127.0.0.1:7200/repositories/telenor-infrastructure-5g4data",
  graphDbInfraNamedGraph: "http://intendproject.eu/telenor/infra",
  graphDbQueryLimit: 0,
  graphDbContextLimit: 10,
  defaultIntentHandler: "inServ",
  defaultIntentOwner: "inChat",
  autoGenerateDescription: true,
  domainPackageDir: "",
  skillFile: "",
  systemPromptFile: "",
  shaclShapesFile: "",
  shaclMaxRetries: 0,
  a2aEnabled: false,
  a2aRegistryBaseUrl: "http://localhost:8000",
  a2aAgentBaseUrl: "http://localhost:3010",
  a2aAgentCardPath: "/.well-known/agent-card.json",
  a2aAutoRegisterOnStartup: true,
  apiServerEnabled: false,
  apiServerHost: "0.0.0.0",
  apiServerPort: 3010,
  agentApiKeyHeader: "X-Api-Key",
  intentReportIntervalMinutes: 10,
  mlflowTracingEnabled: false,
  mlflowTrackingStoreExportEnabled: true
};

test("openai adapter sends configured default temperature", async () => {
  const originalFetch = globalThis.fetch;
  let requestBody: Record<string, unknown> = {};
  globalThis.fetch = (async (_url, init) => {
    requestBody = JSON.parse(String(init?.body)) as Record<string, unknown>;
    return new Response(
      JSON.stringify({
        id: "req_3",
        choices: [{ message: { content: "ok" } }],
        usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 2 }
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  }) as typeof fetch;
  try {
    const invoker = createOpenClawModelInvoker(baseConfig);
    const result = await invoker([{ role: "user", content: "hi" }], { stage: "main_turn" });
    assert.equal(requestBody.model, "gpt-5.3-chat-latest");
    assert.equal(requestBody.temperature, 1);
    assert.equal(result.call.temperature, 1);
    assert.equal(result.call.temperatureSent, true);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test("openai adapter omits temperature when configured to zero", async () => {
  const originalFetch = globalThis.fetch;
  let requestBody: Record<string, unknown> = {};
  globalThis.fetch = (async (_url, init) => {
    requestBody = JSON.parse(String(init?.body)) as Record<string, unknown>;
    return new Response(
      JSON.stringify({
        id: "req_4",
        choices: [{ message: { content: "ok" } }],
        usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 2 }
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  }) as typeof fetch;
  try {
    const invoker = createOpenClawModelInvoker({ ...baseConfig, openAiTemperature: 0 });
    const result = await invoker([{ role: "user", content: "hi" }], { stage: "main_turn" });
    assert.equal("temperature" in requestBody, false);
    assert.equal(result.call.temperature, 0);
    assert.equal(result.call.temperatureSent, false);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test("openai adapter applies session model and temperature overrides", async () => {
  const originalFetch = globalThis.fetch;
  let requestBody: Record<string, unknown> = {};
  globalThis.fetch = (async (_url, init) => {
    requestBody = JSON.parse(String(init?.body)) as Record<string, unknown>;
    return new Response(
      JSON.stringify({
        id: "req_2",
        choices: [{ message: { content: "ok" } }],
        usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 2 }
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  }) as typeof fetch;
  try {
    const invoker = createOpenClawModelInvoker(baseConfig);
    const result = await invoker([{ role: "user", content: "hi" }], {
      stage: "main_turn",
      llmModel: "gpt-4o-mini",
      temperature: 0.7
    });
    assert.equal(requestBody.model, "gpt-4o-mini");
    assert.equal(requestBody.temperature, 0.7);
    assert.equal(result.call.temperature, 0.7);
    assert.equal(result.call.temperatureSent, true);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test("openai adapter captures usage fields", async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = (async () =>
    new Response(
      JSON.stringify({
        id: "req_1",
        choices: [{ message: { content: "ok" } }],
        usage: { prompt_tokens: 100, completion_tokens: 25, total_tokens: 125 }
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    )) as typeof fetch;
  try {
    const invoker = createOpenClawModelInvoker(baseConfig);
    const result = await invoker([{ role: "user", content: "hi" }], { stage: "main_turn" });
    assert.equal(result.call.usage.inputTokens, 100);
    assert.equal(result.call.usage.outputTokens, 25);
    assert.equal(result.call.usage.totalTokens, 125);
    assert.equal(result.call.requestId, "req_1");
  } finally {
    globalThis.fetch = originalFetch;
  }
});
