import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

export interface AppConfig {
  llmProvider: "openai" | "anthropic";
  openAiApiKey: string;
  openAiModel: string;
  openAiBaseUrl: string;
  anthropicApiKey: string;
  anthropicModel: string;
  anthropicBaseUrl: string;
  openClawModel: string;
  workloadCatalogBaseUrl: string;
  graphDbEndpoint: string;
  graphDbNamedGraph: string;
  graphDbQueryLimit: number;
  graphDbContextLimit: number;
  defaultIntentHandler: string;
  defaultIntentOwner: string;
  autoGenerateDescription: boolean;
  domainPackageDir: string;
  skillFile: string;
  systemPromptFile: string;
  shaclShapesFile: string;
  shaclMaxRetries: number;
  llmUsageLogPath?: string;
}

function boolFromEnv(value: string | undefined, fallback: boolean): boolean {
  if (!value) return fallback;
  return ["1", "true", "yes", "on"].includes(value.trim().toLowerCase());
}

function numberFromEnv(value: string | undefined, fallback: number): number {
  if (!value) return fallback;
  const parsed = Number.parseInt(value, 10);
  return Number.isNaN(parsed) ? fallback : parsed;
}

function normalizedBaseUrl(value: string | undefined, fallback: string): string {
  if (value === undefined) return fallback;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : fallback;
}

function mustRead(path: string): string {
  if (!existsSync(path)) {
    throw new Error(`Required file does not exist: ${path}`);
  }
  return readFileSync(path, "utf8");
}

function loadEnvFile(path: string): void {
  if (!existsSync(path)) return;
  const text = readFileSync(path, "utf8");
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    if (!key) continue;
    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

export function loadConfig(): AppConfig {
  // Load env values in this precedence:
  // 1) shell/exported vars (highest, already in process.env)
  // 2) OpenClawAgent/.env
  // 3) HermesAgentReal/.env
  loadEnvFile(resolve(process.cwd(), ".env"));
  loadEnvFile(resolve(process.cwd(), "../HermesAgentReal/.env"));

  const llmProvider = (process.env.LLM_PROVIDER ?? "openai").trim().toLowerCase() as
    | "openai"
    | "anthropic";
  if (!["openai", "anthropic"].includes(llmProvider)) {
    throw new Error("LLM_PROVIDER must be one of: openai, anthropic");
  }

  const openAiModel = process.env.OPENAI_MODEL ?? "gpt-4o-mini";
  const anthropicModel = process.env.ANTHROPIC_MODEL ?? "claude-3-5-sonnet-latest";
  const derivedModel = llmProvider === "openai" ? openAiModel : anthropicModel;

  const skillFile = resolve(
    process.cwd(),
    process.env.SKILL_FILE ?? "../OpenClawPackages/5g4data-intent-generation/skills/SKILL.md"
  );
  const domainPackageDir = resolve(
    process.cwd(),
    process.env.DOMAIN_PACKAGE_DIR ?? "../OpenClawPackages/5g4data-intent-generation"
  );
  const systemPromptFile = resolve(
    process.cwd(),
    process.env.SYSTEM_PROMPT_FILE ?? "../SKILLs/SYSTEM_PROMPT.md"
  );
  const shaclShapesFile = resolve(
    process.cwd(),
    process.env.SHACL_SHAPES_FILE ?? "../HermesAgentReal/validation/skill_subset_intent_shapes.ttl"
  );
  const llmUsageLogPath = process.env.LLM_USAGE_LOG_PATH
    ? resolve(process.cwd(), process.env.LLM_USAGE_LOG_PATH)
    : undefined;

  // Validate at startup so misconfiguration fails fast in OpenClaw.
  mustRead(skillFile);
  mustRead(systemPromptFile);
  if (!existsSync(domainPackageDir)) {
    throw new Error(
      `DOMAIN_PACKAGE_DIR does not exist: ${domainPackageDir}. Set DOMAIN_PACKAGE_DIR to a valid package directory.`
    );
  }

  return {
    llmProvider,
    openAiApiKey: process.env.OPENAI_API_KEY ?? "",
    openAiModel,
    openAiBaseUrl: normalizedBaseUrl(process.env.OPENAI_BASE_URL, "https://api.openai.com/v1"),
    anthropicApiKey: process.env.ANTHROPIC_API_KEY ?? "",
    anthropicModel,
    anthropicBaseUrl: normalizedBaseUrl(
      process.env.ANTHROPIC_BASE_URL,
      "https://api.anthropic.com"
    ),
    openClawModel: process.env.OPENCLAW_MODEL ?? derivedModel,
    workloadCatalogBaseUrl:
      process.env.WORKLOAD_CATALOG_BASE_URL ?? "https://start5g-1.cs.uit.no/wchartmuseum",
    graphDbEndpoint:
      process.env.GRAPHDB_ENDPOINT ??
      "https://start5g-1.cs.uit.no/graphdb/repositories/intents_and_intent_reports",
    graphDbNamedGraph: process.env.GRAPHDB_NAMED_GRAPH ?? "http://intendproject.eu/telenor/infra",
    graphDbQueryLimit: Math.max(0, numberFromEnv(process.env.GRAPHDB_QUERY_LIMIT, 0)),
    graphDbContextLimit: Math.max(1, numberFromEnv(process.env.GRAPHDB_CONTEXT_LIMIT, 10)),
    defaultIntentHandler: process.env.DEFAULT_INTENT_HANDLER ?? "inServ",
    defaultIntentOwner: process.env.DEFAULT_INTENT_OWNER ?? "inChat",
    autoGenerateDescription: boolFromEnv(process.env.AUTO_GENERATE_DESCRIPTION, true),
    domainPackageDir,
    skillFile,
    systemPromptFile,
    shaclShapesFile,
    shaclMaxRetries: Math.max(0, numberFromEnv(process.env.SHACL_MAX_RETRIES, 2)),
    llmUsageLogPath
  };
}

export function readConfigFileText(path: string): string {
  return mustRead(path).trim();
}

export function resolveProjectRoot(): string {
  return rootSafe(process.cwd(), "..");
}

function rootSafe(base: string, relative: string): string {
  return resolve(base, relative);
}
