intent:
  objectives:
    - name: detection-latency
      value: "0.0"
      tmf-value-hint: "5000"
      tmf-quantifier-hint: "quan:smaller"
      tmf-unit-hint: "ms"
      measuredBy: intend/detectionlatency
  sustainability:
    - name: container-cpu-joules-total
      value: "5000.0"
      tmf-value-hint: "5000"
      tmf-quantifier-hint: "quan:larger"
      tmf-unit-hint: "J"
      measuredBy: intend/container-cpu-joules-total
    - name: container-cpu-watts
      value: "5000.0"
      tmf-value-hint: "5000"
      tmf-quantifier-hint: "quan:smaller"
      tmf-unit-hint: "W"
      measuredBy: intend/container-cpu_watts